In [17]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [18]:
class SimpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
    
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [19]:
net = SimpleNet()
print(net.W)

[[-1.79015447  0.74072654 -1.54278635]
 [ 1.16126753 -2.41655304  1.01214304]]


In [20]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-0.0289519  -1.73046181 -0.01474307]


In [21]:
np.argmax(p)

2

In [22]:
t = np.array([0, 0, 1])
net.loss(x, t)

0.7727556686199597

def f(W):
    return net.loss(x, t)

In [27]:
f = lambda W: net.loss(x, t)

In [28]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.27314365  0.04982057 -0.32296422]
 [ 0.40971547  0.07473085 -0.48444633]]
