In [6]:
import numpy as np
A = np.array([1, 2, 3, 4])
print(A)
np.ndim(A)

[1 2 3 4]


1

In [7]:
A.shape ## 4행 1열 / 1행 4열

(4,)

In [8]:
A.shape[0] # 첫번째 차원의 원소 개수 출력

4

In [9]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
np.ndim(B)

2

In [11]:
B.shape

(3, 2)

In [12]:
B.shape[0]

3

In [13]:
B.shape[1]

2

In [14]:
## np.dot(A, B)에 대하여 알아보자
# case 1) A와 B가 모두 2차원 배열인 경우 => 행렬의 곱
# case 2) A와 B가 모두 1차원 배열인 경우 => 벡터의 내적을 계산한다.
# case 3) A와 B중 하나는 1차원 배열, 하나는 2차원 배열인 경우 => 벡터를 행렬로 간주하고 행렬의 곱을 진행한다. 
                                                    # (1차원 배열인 벡터는 n행 1열로도 볼 수 있고, 1행 n열로도 볼 수 있다.)

In [20]:
## case 1)
A = np.array([[1, 2, 3], [4, 5, 6]]) # 2행 3열
B = np.array([[1, 2], [3, 4], [5, 6]]) # 3행 2열
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [23]:
## case 2)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
np.dot(A, B)

32

In [21]:
## case 3)
A = np.array([[1, 2], [3, 4], [5, 6]]) # 3행 2열
B = np.array([7, 8]) # 1차원 배열 => 벡터 => 이 상황에서는 2행 1열 행열로 간주
np.dot(A, B)

array([23, 53, 83])

In [24]:
A = np.array([7, 8]) # 1차원 배열 => 벡터 => 이 상황에서는 1행 2열 행열로 간주
B = np.array([[1, 2, 3], [4, 5, 6]]) # 2행 3열
np.dot(A, B)

array([39, 54, 69])